name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Choose the appropriate Node.js version

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/your-image-name:${{ github.sha }} .
      working-directory: ./Dockerhub

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          ecr: auto
          username: nagagogulan
          password: dckr_pat_X0rWbGoWE_nPgoQA9wDq7IN1A8c



    - name: Push Docker image
      run: |
       docker push nagagogulan/node1:cef193a40157454929697fe39a2416551c554a3c
       docker tag nagagogulan/node1:cef193a40157454929697fe39a2416551c554a3c nagagogulan/node1:latest
       
       
